### ISSUE TITLE
[feat] defaultsValues

### ISSUE THREAD

**Issue by andreineculau** [tobiipro/lodash-firecloud#19]
@IanSavchenko do you see another=simpler way of achieving this https://github.com/tobiipro/gs-client/blob/3376e16b4f4704f7ad2f447e6420778fa3b85d31/.eslintrc.js#L95-L117 ?
with lodash built-ins ? it's a defaultsDeep down to 1-level only

otherwise I intend to move that in here. at least temporarily, that function will need to be used in all (currently 3) repos where we use typescript, because a lack of functionality in eslint's `overrides`

**Comment by IanSavchenko** [comment]
It seems to be correct, but I wouldn't move it here. Looks very specific to this use case and the naming does not say much (`defaultsDeep down to 1-level only` is a much better description than `defaultsValues`). 

 Maybe SF?

Btw, in this line, the right-hand side mutates the first objsKey (which I would call `objsValue`, probably). Don't know if it's a problem, but still...
```
      acc[key] = _.defaults(...objsKey);
```

**Comment by andreineculau** [comment]
since it's related to eslint, it could actually be moved to eslint-config-firecloud
