### ISSUE TITLE
Lodash-firecloud has peer deps, but no install-peer-deps script like other subrepos

### ISSUE THREAD

**Issue by IanSavchenko** [tobiipro/lodash-firecloud#4]

**Comment by andreineculau** [comment]
i don't see the need for one. the other ones - a babel-preset and a eslint-config - have the `npm-install-peer-dependencies` script as a convenience, not as a necessity

what should happen is to have *bluebird as a prod dependency*, until we can actually bump to nodejs 8 and remove it altogether
